ISI_Chat/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = ''
admin.site.site_header = 'ISI Chat Administartion'
admin.site.site_title = 'ISI Chat Administartion'
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('Getlogin/', views.getlogin, name='Getlogin'),
    path('logout/', views.logout, name='logout'),
    path('chat/', include('chat.urls')),
    path('profile/', include('Profile.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Profile/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path('SingUp/', views.singup, name='singup'),
    path('SingUping/', views.getsingup, name='getsingup'),
    path('updat/', views.updateprofile, name='updp'),
    path('ulimg/', views.UploadUserAvatar, name='upimg'),
    path('dlimg/', views.DeleteAvatare, name='dlimg'),
    path('<slug:slug>/', views.profile, name='pfle'),
]

chat/urls.py
from django.urls import path, include
from . import views

app_name = 'chats'
urlpatterns = [
    path('rooms/', views.rooms, name='rooms'),
    path('<slug:slug>', views.chatroom, name='chatr'),
    path('sendImage/', views.uploadImageFromRoom, name='chatr'),

]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
import os
# Create your models here.



def UploadTo(instence, filename):
    ext = '.'+filename.split('.')[-1]
    filename = 'avatar'+instence.user.username+ext
    return filename


class UserProfil(models.Model):
    SEXE = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    DateBirth = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(upload_to=UploadTo)
    gender = models.CharField(max_length=10, choices=SEXE)


    def __str__(self):
        return self.user.username

Profile/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class DateInput(forms.DateInput):
    input_type = 'date'


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2'
        ]


class CreateProfile(forms.ModelForm):
    class Meta:
        model = models.UserProfil
        fields = ['gender']
        widgets = {
            'DateBirth': DateInput()
        }


class UploadAvatar(forms.Form):
    avatar = forms.ImageField()

Profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from datetime import datetime
from django.utils.translation import gettext as _
from .models import UserProfil
from . import forms
# Create your views here.


def singup(request):
    formsgup = forms.RegistrationForm()
    formsCus = forms.CreateProfile()
    activeS = "active"
    return render(request, 'Singup.html', locals())


def getsingup(request):

    if request.method == 'POST':
        userform = forms.RegistrationForm(request.POST)
        profileform = forms.CreateProfile(request.POST)
        if userform.is_valid() and profileform.is_valid():
            user = userform.save()
            pfile = profileform.save(commit=False)
            pfile.user = user
            if request.POST['gender'] == 'M':
                pfile.photo = "DefAvtM.png"
            else:
                pfile.photo = "DefAvtF.png"
            pfile.save()
            user = authenticate(request, username=request.POST['username'], password=request.POST['password1'])
            auth_login(request, user)
            activeI = "active"
            return render(request, 'index.html')
        else:
            formsgup = forms.RegistrationForm()
            formsCus = forms.CreateProfile()
            ErrMessage = _('Some of data is incorrect')
            activeS = "active"
            return render(request, 'Singup.html', locals())


@login_required(login_url="login")
def profile(request, slug):
    SLUG = slug
    user = request.user
    uprofile = UserProfil.objects.get(user=user)
    formsgup = forms.RegistrationForm()
    formsCus = forms.CreateProfile()
    formImg = forms.UploadAvatar()
    if uprofile.DateBirth:
        dateb = uprofile.DateBirth.strftime('%Y-%m-%d')
    if uprofile.gender == 'F':
        bgS = 'rgba(165, 41, 115, 0.9)'
    else:
        bgS = 'rgba(16, 87, 140, 0.88)'
    if request.method == 'POST':
        if request.POST['UpPass']:
            u = authenticate(username=uprofile.user.username, password=request.POST['OldPass'])
            if u:
                if request.POST['password1'] == request.POST['password2']:
                    uprofile.user.set_password(request.POST['password1'])
                    uprofile.user.save()
                    uprofile.save()
                    SccMessage = _('Your password changed successfully')
                else:
                    ErrMessage = 'The passwords are not the same'
            else:
                ErrMessage = 'Old password is incorrect'
    activeP = "active"
    return render(request, 'profile.html', locals())


def updateprofile(request):
    if request.method == 'POST':
        udprofile = UserProfil.objects.get(user=request.user)
        udprofile.user.username = request.POST['username']
        udprofile.user.first_name = request.POST['first_name']
        udprofile.user.last_name = request.POST['last_name']
        udprofile.gender = request.POST['gender']
        udprofile.DateBirth = datetime.strptime(request.POST['DateBirth'], '%Y-%m-%d').date()
        udprofile.user.email = request.POST['email']
        udprofile.user.save()
        udprofile.save()

    return redirect('profile:pfle', slug=request.user)


def UploadUserAvatar(request):
    if request.method == 'POST':
        imgForm = forms.UploadAvatar(request.POST, request.FILES)
        if imgForm.is_valid():
            uprofile = UserProfil.objects.get(user=request.user)
            uprofile.photo = imgForm.cleaned_data['avatar']
            uprofile.save()

    return redirect('profile:pfle', slug=request.user)


def DeleteAvatare(request):
    if request.method == 'POST':
        uprf = UserProfil.objects.get(user=request.user)
        if uprf.gender == 'M':
            uprf.photo = 'DefAvtM.png'
        else:
            uprf.photo = 'DefAvtF.png'
        uprf.save()
    return redirect('profile:pfle', slug=request.user)

templates/Login.html
{% extends 'baseLayout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans ' - Log in' %}
{% endblock %}
{% block content %}
    <div class="container h-auto">
       <div class="row">
           <div class="col-12 col-sm-10 col-md-9 col-lg-6 m-auto">
                <form method="post" class="m-5 border border-info p-3 rounded" action="{% url 'Getlogin' %}">
                        <h4 class="text-center text-capitalize border-bottom pb-3"><i class="fas fa-sign-in-alt"></i> {% trans 'Log in' %}</h4>
                    <br>
                    {% csrf_token %}
                    <small class="text-danger">{{ ErrMessage }}</small>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{% trans 'Username' %}</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" name="username" placeholder="{% trans 'username' %}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">{% trans 'Password' %}</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="{% trans 'Password' %}">
                    </div>
                    <button type="submit" class="btn btn-primary">{% trans 'Log in' %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/Singup.html
{% extends 'baseLayout.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}
    {% trans ' - Sing up' %}
{% endblock %}
{% block CustomCSS %}
    <style>
      body, html { height: 100%}
      main {
         height: 100%;
      }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="font-weight-bold m-4 col-12 text-center"> <i class="fas fa-user-plus"></i> {% trans 'Sing Up' %}</h1>
        <div class="col-12 col-sm-10 col-md-8 col-lg-5 d-block mx-auto">
            {% if ErrMessage %}
          <sapn class="text-danger m-3">{{ ErrMessage }}</sapn>
            {% endif %}
            <form action="{% url 'profile:getsingup' %}" method="post" class="mt-3">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-4 col-form-label">{% trans 'Username' %}</label>
                    <div class="col-sm-8">
                      {{ formsgup.username|add_class:'form-control' }}
                    </div>
                 </div>

                <div class="form-group row">
                <label for="inputEmail3" class="col-sm-4 col-form-label">{% trans 'First name' %}</label>
                <div class="col-sm-8">
                  {{ formsgup.first_name|add_class:'form-control' }}
                </div>
              </div>
                <div class="form-group row">
                <label for="inputEmail3" class="col-sm-4 col-form-label">{% trans 'Last name' %}</label>
                <div class="col-sm-8">
                  {{ formsgup.last_name|add_class:'form-control' }}
                </div>
              </div>
                  <div class="form-group row">
                <label for="inputPassword3" class="col-sm-4 col-form-label">{% trans 'Gender' %}</label>
                <div class="col-sm-8">
                    {{ formsCus.gender|add_class:'form-control' }}
                </div>
              </div>
              <div class="form-group row">
                <label for="inputEmail3" class="col-sm-4 col-form-label">{% trans 'email' %}</label>
                <div class="col-sm-8">
                  {{ formsgup.email|add_class:'form-control' }}
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-4 col-form-label">{% trans 'Password' %}</label>
                <div class="col-sm-8">
                 {{ formsgup.password1|add_class:'form-control' }}
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPassword3" class="col-sm-4 col-form-label">{% trans 'Password confirmation' %}</label>
                <div class="col-sm-8">
                 {{ formsgup.password2|add_class:'form-control' }}
                </div>
              </div>

              <div class="form-group row">
                <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary">Sign up</button>
                </div>
              </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/baseLayout.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ISI Chat
        {% block title %}

        {% endblock %}

    </title>
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/emoji/emojionearea.min.css' %}">
    {% block CustomCSS %}
    {% endblock %}
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <a class="navbar-brand logoFont" href="{% url 'home' %}">ISI Chat</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item {{ activeI }}">
                <a class="nav-link" href="{% url 'home' %}">{% trans 'Home' %} <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item {{ activeR }}">
                <a class="nav-link" href="{% url 'chats:rooms' %}">{% trans 'Rooms' %}</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item {{ activeP }}">
                <a class="nav-link" href="{% url 'profile:pfle' slug=user.get_username %}">{% trans 'Profile' %}</a>
              </li>
                {% if user.is_staff %}
                  <li class="nav-item">
                   <a class="nav-link"  href="/admin/">{% trans 'Administration' %}</a>
                  </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
              </li>
              {% else %}
               <li class="nav-item {{ activeS }}">
                <a class="nav-link" href="{% url 'profile:singup' %}">{% trans 'Singup' %}</a>
              </li>
              <li class="nav-item {{ activeL }}">
                <a class="nav-link" href="{% url 'login' %}">{% trans 'Login' %}</a>
              </li>
             {% endif %}
            </ul>
            <span class="navbar-text">
              {% if user.is_authenticated %}
                {% trans 'welcome' %} {{ user.get_username }}
              {% endif %}
            </span>
          </div>
        </nav>
        <header class="space"></header>
        <div class="imgchat p-0 m-0 w-100 h-100">
            <div class="row bg-isi p-3">
                 <div class="float-left p-2">
                     <img src="/media/website/IsiChatLogoLight.png" alt="logoIsichat" width="100" height="100">
                </div>
                    <div class="col-md-10">
                        <h1 class="ml-5 title-page">{% trans 'Isi Chat rooms' %}</h1>
                       {% block descretion %}
                       {% endblock %}
                    </div>
                </div>
        </div>
    </div>
    <main class="container-fluid p-0 h-100">

    {% block content %}
    
    {% endblock %}
    </main>
    <footer class="w-100 bg-dark">
            <h5 class="text-light text-center pt-4">ISI Chat | {% trans 'All right reserved' %}</h5>
    </footer>
    <script type="text/javascript" src="{% static 'javascript/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/vue.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/emoji/emojionearea.js' %}"></script>
    {% block CustomJS %}
    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'baseLayout.html' %}
{% load i18n %}
{% block CustomCSS %}
    <style>
        main {
            background-color: #343334 !important;
            color: #efdab9 !important;
        }
        .imgchat {
            background: none;
        }
    </style>
{% endblock %}

{% block descretion %}


            <p class="text-light text-center" > Let's Chat a Subject</p>

{% endblock %}
{% block content %}
      <video autoplay muted loop id="Videochat">
                  <source src="/media/website/videochating.mp4" type="video/mp4">
                </video>

 <div class="p-3 text-center intro">
    <h1>{% trans 'Welcom to our chat rooms' %}</h1>
    <p class="pt-2">{% trans "To have a cultured knowledge you can read, watch or just listen to your favorite and what interest  you of subjects, that's good and very productive. So what if you add to this ways chatting and discussing this subject ? Well, you will extend your knowledge not only in your cultured information, but also in how others think and see thos subjects and what they know, so here you can share and learn or like one of my friends said share is learn." %}</p>
    <p class="">{% trans "Sing up, choose a room, and start chatting a subject" %}</p>
 </div>
 <div id="carouselExampleIndicators" class="carousel slide m-auto" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    {% for n in nbr %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{ n }}"></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/media/website/IsiChatCarousl0.png" width="1500px" height="500px" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
            <h1 class="text-black-50 nameroom">Isi Chat</h1>
            <p>...</p>
          </div>
    </div>
      {% for room in rooms %}
       <div class="carousel-item">
          <img class="d-block w-100" src="{{ room.photo.url }}" width="1500px" height="500px" alt="slide_{{ room }}">
            <div class="carousel-caption d-none d-md-block">
            <h1 class="text-black-50 nameroom">{{ room }}</h1>
            <p>...</p>
          </div>
        </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}

{% block CustomJS %}

{% endblock %}

templates/profile.html
{% extends 'baseLayout.html' %}
{% load i18n %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}
    {% trans 'My profile' %}
{% endblock %}
{% block CustomCSS %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
        <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
{% endblock %}
{% block content %}

    <h1 class="font-weight-bold col-12 title-page text-dark pt-2">{{ user.get_username }}'s Profile </h1>
    {% if SccMessage %}
        <div class="alert alert-success" role="alert">
          <i class="far fa-check-circle"></i> {{ SccMessage }}
        </div>
    {% endif %}
     {% if ErrMessage %}
        <div class="alert alert-danger" role="alert">
          <i class="far fa-times-circle"></i> {{ ErrMessage }}
        </div>
    {% endif %}
    <div class="row mt-5">
            <div class="col-12 col-sm-4 col-md-4 col-lg-3 text-center p-0 dashboard">
            <img src="{{ uprofile.photo.url }}" alt="{{ user.get_username }}'s Profile" style="height: 300px" class="img-thumbnail col-12 col-sm-12 col-md-12 col-lg-8 m-1 p-0">
            <div class="col-12 m-1">
                <button class="btn btn-warning m-1" onclick="ShowUpload()">{% trans 'change Photo' %}</button>
                <form action="{% url 'profile:dlimg' %}" method="post" class="p-0 m-0 d-inline">
                    {% csrf_token %}
                    <button class="btn btn-danger m-1">{% trans 'Delete Photo' %}</button>
                </form>
            </div>
            <form class="form-control m-2 row" id="formAvatar" action="{% url 'profile:upimg' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ formImg.avatar|add_class:'form-control col-12 d-inline' }}
                <button type="submit" class="btn btn-success m-2 col-6">{% trans 'Update avatar' %}</button>
            </form>
        </div>
        <div class="col-12 col-sm-8 col-md-8 col-lg-9">
            <table class="table table-responsive w-75 d-table" style="height: 375px">
                 <tr>
                    <th class="w-25">{% trans 'Username' %} : </th>
                    <td>{{ user.get_username }}</td>
                </tr>
                <tr>
                    <th>{% trans 'Name' %} : </th>
                    <td>{{ uprofile.user.first_name }}</td>
                </tr>
                 <tr>
                    <th>{% trans 'Laste name' %} : </th>
                    <td>{{ uprofile.user.last_name }}</td>
                </tr>
                <tr>
                    <th>{% trans 'Gender' %} : </th>
                    <td>
                        {% if uprofile.gender == 'M' %}
                            {% trans 'Male' %}
                        {% else %}
                            {% trans 'Female' %}
                        {% endif %}

                    </td>
                </tr>
                <tr>
                    <th>{% trans 'Date of birth' %} : </th>
                    <td>{{ uprofile.DateBirth|date:'b d, Y' }}</td>
                </tr>
                <tr>
                    <th>{% trans 'Email' %} : </th>
                    <td>{{ uprofile.user.email }}</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <button class="btn btn-dark m-1" data-toggle="modal" data-target="#myModal">{% trans 'Edit Profile' %}</button>
                        <button class="btn btn-outline-info m-1" data-toggle="modal" data-target="#myModal2">{% trans 'change passeword' %}</button>
                    </td>

                </tr>
            </table>
        </div>
    </div>

<!-- ---------------------------------------------------------------------------------------------------------->
<!-- -----------------------------------------UPDATE PROFILE -------------------------------------------------->
<!-- Modal content-->

    <div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

<div class="modal-content" style="background: {{ bgS }}">
<div class="modal-header">

<h4 class="modal-title">{% trans 'Edit profile' %}</h4>
<button type="button" class="close" data-dismiss="modal">×</button>
</div>
<div class="modal-body">

        <form role="form" method="post" id="reused_form" action="{% url 'profile:updp' %}" >
            {% csrf_token %}
        <div class="form-group">
            <label for="username">{% trans 'Username' %}:</label>
            {% render_field formsgup.username value=uprofile.user.username class='form-control' %}
        </div>
        <div class="form-group">
            <label for="first_name">
                {% trans 'First name' %}</label>
            {% render_field formsgup.first_name value=uprofile.user.first_name class='form-control' %}
        </div>
         <div class="form-group">
            <label for="last_name">
                {% trans 'Laste name' %}</label>
           {% render_field formsgup.last_name value=uprofile.user.last_name class='form-control' %}
        </div>
         <div class="form-group">
            <label for="gender">
                {% trans 'Gender' %}</label>
             <select id="id_gender" name="gender" class="form-control" required>
            {% for value, key in formsCus.gender.field.choices %}
                <option value="{{ value }}" {% if uprofile.gender == value %} selected="selected" {% endif %}>
                    {{ key }}
                </option>
            {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="DateBirth">
                {% trans 'Date of birth' %}</label>
           {% render_field formsCus.DateBirth value=dateb class='form-control' %}
        </div>
         <div class="form-group">
            <label for="email">
                {% trans 'E-mail' %}</label>
           {% render_field formsgup.email value=uprofile.user.email class='form-control' %}
        </div>
        <button type="submit" class="btn btn-lg btn-success btn-block" id="btnContactUs">{% trans 'Update profile' %}</button>

    </form>
    <div id="success_message" style="width:100%; height:100%; display:none; ">
        <h3>Sent your message successfully!</h3>
    </div>
    <div id="error_message"
    style="width:100%; height:100%; display:none; ">
        <h3>Error</h3>
        Sorry there was an error sending your form.

    </div>
</div>

</div>

 </div>
</div>


<!-- ---------------------------------------------------------------------------------------------------------->
<!-- -----------------------------------------UPDATE PASSWORD -------------------------------------------------->
<!-- Modal content-->

    <div id="myModal2" class="modal fade" role="dialog">
  <div class="modal-dialog">

<div class="modal-content" style="background: {{ bgS }}">
<div class="modal-header">

<h4 class="modal-title">{% trans 'Edit password' %}</h4>
<button type="button" class="close" data-dismiss="modal">×</button>
</div>
<div class="modal-body">

        <form role="form" method="post" id="reused_form" action="{% url 'profile:pfle' slug=user.get_username %}" >
            {% csrf_token %}
            <p class="text-danger">{{ ErrMessage }}</p>
        <div class="form-group">
            <label for="username">{% trans 'Old password' %}:</label>
            <input type="password" name="OldPass" class="form-control" required="" id="id_OldPass">
        </div>
        <div class="form-group">
            <label for="first_name">
                {% trans 'New Password' %}</label>
            {% render_field formsgup.password1 class='form-control' %}
        </div>
         <div class="form-group">
            <label for="first_name">
                {% trans 'Password confirmation' %}</label>
            {% render_field formsgup.password2 class='form-control' %}
        </div>

        <button type="submit" class="btn btn-lg btn-success btn-block" name="UpPass" value="Update password" id="btnContactUs">{% trans 'Update password' %}</button>

    </form>
    <div id="success_message" style="width:100%; height:100%; display:none; ">
        <h3>Sent your message successfully!</h3>
    </div>
    <div id="error_message"
    style="width:100%; height:100%; display:none; ">
        <h3>Error</h3>
        Sorry there was an error sending your form.

    </div>
</div>

</div>

 </div>
</div>
{% endblock %}
{% block CustomJS %}
    <script src="{% static 'javascript/form.js' %}"></script>
    <script>
     $('#formAvatar').hide();
        function ShowUpload(){
            if ($('#formAvatar').is(":hidden")) {
                $('#formAvatar').show();
            }else {
                $('#formAvatar').hide();
            }

        }
    </script>
{% endblock %}

templates/rooms.html
{% extends 'baseLayout.html' %}
{% load i18n %}
{% load static %}
{% block title %}
    {% trans 'Rooms' %}
{% endblock %}
{% block CustomJS %}
    <style>
        main {
            height: 100%;
            z-index: 0;
        }
    </style>
{% endblock %}
{% block content %}

    <h1 class="title-page text-dark m-2"> <i class="fas fa-door-open"></i> {% trans 'Rooms' %}</h1>
    <div class="container mt-5 p-0">
        <div class="row">
            {% for room in rooms %}
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-2">
                       <a class="font-weight-bold" href="{% url 'chats:chatr' slug=room %}#roomtitle">
                           <div class="btn-outline-info text-dark p-2 border border-info">
                               <img src="{{ room.photo.url }}" width="98%" height="200px" alt="">
                               <span class="">{{ room }}</span>
                               <span class="float-right">
                                   <i class="fas fa-users"></i>
                                    {% for key, value in dataP.items %}
                                            {% ifequal key room.nameRoom %}
                                               {{value}}
                                            {% endifequal %}
                                   {% endfor %}
                               </span>
                            </div>
                       </a>
                    </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/testjs.html
{% extends 'baseLayout.html' %}
{% load static %}
{% load i18n %}
{% block title %}
    {% trans ' - Chat' %}
{% endblock %}
{% block content %}
    <h1>Hello test</h1>
     <div id="msgcanva" class="border-info col-12 h-50" >
        <div class="col-10 border-bottom">
            <h4><img src="{% static 'img/prof1.jpg' %}" style="border-radius: 50px" height="50px" width="50px" alt="photo">
            {{ user.get_username }} : <small>Hello there</small> </h4>
        </div>
    </div>

{% endblock %}

 {% block CustomJS %}
    <script>
        alert('hey');
    </script>
            {% endblock %}